#  ______  __  __          _    _____ _             
# |  ____|/ _|/ _|        | |  / ____| |            
# |  __| |  _|  _/ _ \/ __| __|\___ \| __/ _` | '__|
# | |____| | | ||  __/ (__| |_ ____) | || (_| | |   
# |______|_| |_| \___|\___|\__|_____/ \__\__,_|_|   
                                                  
Item ID: 399
# ^^ Choses Whitch Item Will Be Tapped On The Ground To Give The Effect
Effect ID: 5 
# ^^ 5 is the effect id for strength
Effect Duration: 6000
# ^^ 6 Seconds Is how Long The Effect will be given for
Effect Amp: 2
# ^^ This Means That The Player Will Recieve Strength 2
Effect Visible: true
# ^^ If this is false the player will not see any particles

 #______  __  __          _     _____ _____   _____ 
 #|  ____|/ _|/ _|        | |   |_   _|  __ \ / ____|
 #| |__  | |_| |_ ___  ___| |_    | | | |  | | (___  
 #|  __| |  _|  _/ _ \/ __| __|   | | | |  | |\___ \ 
 #| |____| | | ||  __/ (__| |_   _| |_| |__| |____) |
 #|______|_| |_| \___|\___|\__| |_____|_____/|_____/ 
 #Im only listing Some Important Ones

#Speed: 1
#Slowness: 2
#Haste: 3
#Mining Fatigue: 4
#Strength: 5
#Jump Boost: 8
#Nausea: 9
#Regeneration: 10
#Resistance: 11
#Fire Resistance: 12
#Water Breathing: 13
#Invisiblility: 14
#Blindness: 15
#Night Vision: 16
#Hunger: 17
#Weakness: 18
                                                    
